import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import {ClerkProvider} from "@clerk/nextjs";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <ClerkProvider appearance={{layout:{
      logoImageUrl: "/icons/StreamSyncLogoDark.svg",
        socialButtonsVariant: "iconButton",
        socialButtonsPlacement: "bottom"
    },
      variables:{
        colorText: "#fff",
        colorPrimary: "#0E78F9",
        colorBackground: "#1c1f2e",
        colorInputBackground: "#252a41",
        colorInputText: "#fff"
      }
    }}>
      <body
        className={`${inter.className} bg-[var(--color-dark-2)] antialiased`}
      >
        {children}
      </body>
    </ClerkProvider>
    </html>
  );
}
